lsi: false
safe: true
source: https://github.com/ec-jrc/cbm
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-leap-day
title: CAP - Checks by Monitoring (CbM)
description: Code examples developed by GTCAP-JRC